import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Disney Plus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <div className="bg-black flex flex-col w-full my-0 mx-auto text-white items-center">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
